# Generated by Django 4.2.20 on 2025-04-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='footer_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='header_content',
        ),
    ]
